# Q1:
# Create a Streamlit application that allows users to upload a CSV file and view its schema.Use an LLM to convert user questions into SQL queries, execute them on the CSV data using pandasql, and explain the results in simple English.

import streamlit as st
import pandas as pd
from langchain_groq import ChatGroq
from pandasql import sqldf
import os



st.title("Ask CSV using SQL (Groq)")

llm = ChatGroq(
    model="meta-llama-3.1-8b-instruct",
    api_key=st.secrets["GROQ_API_KEY"]
)


uploaded_file = st.file_uploader("Upload CSV file", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)

    st.subheader("CSV Schema")
    st.write(df.dtypes)

    schema = "\n".join([f"{col} ({dtype})" for col, dtype in df.dtypes.items()])

    question = st.text_input("Ask anything about this CSV:")

    if question:
        prompt = f"""
        Table Name: data
        Table Schema:
        {schema}

        Question: {question}

        Instructions:
        - Write ONLY a valid SQLite SELECT query
        - Use ONLY table name: data
        - Do NOT add explanation
        - Do NOT use markdown
        """

        result = llm.invoke(prompt)
        sql_query = result.content.strip()

        if sql_query.startswith("```"):
            sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

        if not sql_query.lower().startswith("select"):
            st.error("Invalid SQL generated by LLM")
            st.stop()

        st.subheader("Generated SQL")
        st.code(sql_query, language="sql")

        try:
            query_result = sqldf(sql_query, {"data": df})

            st.subheader("Query Result")
            st.dataframe(query_result)

            explanation_prompt = f"""
            Explain the following query result in simple English:

            {query_result}
            """

            explanation = llm.invoke(explanation_prompt)

            st.subheader("Explanation")
            st.write(explanation.content.strip())

        except Exception as e:
            st.error(f"SQL Execution Error: {e}")